apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-ui-app
  template:
    metadata:
      labels:
        app: todo-ui-app
    spec:
      containers:
      - name: todo-ui-app
        image: todomicroservicesacr1234.azurecr.io/todo-ui-app:latest
        ports:
        - containerPort: 80
