apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-task-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: get-task
  template:
    metadata:
      labels:
        app: get-task
    spec:
      containers:
      - name: get-task
        image: todomicroservicesacr1234.azurecr.io/get-todo-app:latest
        ports:
        - containerPort: 8000 
