apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-task-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delete-task
  template:
    metadata:
      labels:
        app: delete-task
    spec:
      containers:
      - name: Delete-Task-Deployment
        image: todomicroservicesacr1234.azurecr.io/delete-todo-app:latest
        ports:
        - containerPort: 8000
