apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delete-task-ingress

spec:
  inggressClassName: azure-application-gateway
  rules:
    - host: deletetask.puneetdevops.online
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: delete-task
                port:
                  number: 80
