apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-todoui-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PuneetKSharma-O/Todo_App_Microservices.git'
    targetRevision: main
    path: ./Micro-todo-ui/manifest/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-todo-addtask-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PuneetKSharma-O/Todo_App_Microservices.git'
    targetRevision: main
    path: ./Add-Task/manifest/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-todo-deletetask-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PuneetKSharma-O/Todo_App_Microservices.git'
    targetRevision: main
    path: ./Delete-task/manifest/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-todo-get-task-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PuneetKSharma-O/Todo_App_Microservices.git'
    targetRevision: main
    path: ./Get-Task/manifest/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  