apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-task-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
    spec:
      containers:
        - name: add-task-deployment
          image: todomicroservicesacr1234.azurecr.io/add-todo-app:latest
          ports:
            - containerPort: 8000
