name: dev-pipeline
on: 
  pull_request:
    branches:
      - main
    paths:
      - Environment/dev/**
  push: 
    branches:
      - main
    paths:
      - Environment/dev/**

permissions:
  id-token: write
  contents: read

env:
  working-directory: Environment/dev

jobs:
  terraform_Build_Job:
    name: Terraform Build & Plan
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login (OIDC)
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform_fmt
        id: fmt
        run: terraform fmt -check
        working-directory: Environment/dev 
