name: dev-pipeline
on: workflow_dispatch
#   pull_request:
#     branches:
#       - main
#     paths:
#       - Environment/dev/**
#   push:
#     branches:
#       - main
#     paths:
#       - Environment/dev/**

permissions:
  id-token: write
  contents: read

jobs:
  Terraform_Build_Job:
    name: Build_Job
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: e8603241-474b-4633-bb9c-6ec410cf1e6d
          tenant-id: 5a2c20bc-546f-43e0-b1a8-41fcb1f0c95c
          subscription-id: 470e0441-3f52-4fdf-8fc5-508cd114ccbc

      - name: Terraform_fmt
        id: fmt
        run: terraform fmt -check
        working-directory: Environment/dev 
